#!/usr/bin/Rscript

# Load libraries
library(tidyverse)
library(glue)
library(RMINC)

# Get input files - WT154
# Point to resampled determinants generated by Jacob
df <- read_csv("data/resources/scanbase_mice_used.csv") %>%
  select(Mouse_ID:Mouse_Sex, Mouse_Age, Genotype_Code, Is_Wildtype:Background, Treatment_Code, Scan_Type:Distortion_Corrected_Scan, Scan_To_Study_Global_Space_Resampled_Absolute_Jacobians, Collaborator_Name:Publications, Notes) %>%
  mutate(resampled_determinants_CCFv3_abs_50=glue("data/resources/jacobian_determinants/abs_50/{Mouse_ID}_abs_50.mnc"),
         resampled_determinants_CCFv3_abs_200=glue("data/resources/jacobian_determinants/abs_200/{Mouse_ID}_abs_200.mnc"))

# Do all files exist?
print(glue("All determinants exist at 50um?: {all(file.exists(df$resampled_determinants_CCFv3_abs_50))}"))
print(glue("All determinants exist at 200um?: {all(file.exists(df$resampled_determinants_CCFv3_abs_200))}"))

# Get cortex and thalamus volumes
# Takes 3-4 minutes to run on fievel
vols <- anatGetAll(filenames = df$resampled_determinants_CCFv3_abs_50, 
                   atlas = "data/outputs/masks/combined_label_set_50um.mnc", # Volumes of both sides
                   defs ="data/outputs/masks/combined_label_set_defs.csv",
                   method = "jacobians")

df <- df %>% cbind(vols %>% as_tibble)
write_csv(df, "data/outputs/wt154.csv")